version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: tanaka0
      POSTGRES_PASSWORD: P@ssword@303
      POSTGRES_DB: system
    ports:
      - "5332:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

